version: "3.8"
services:
  server:
    name: streaming-server
    image: streaming.service
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

    ports:
      - "8080:8080"
    command: --address :8080
